server:
  port: 8080

spring:
  application:
    name: soulsync-backend
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/soulsync}
      database: soulsync
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:}

# OpenAI Configuration
openai:
  api:
    key: ${OPENAI_API_KEY:}

# AWS Configuration
aws:
  region: ${AWS_REGION:us-east-1}
  lambda:
    sentiment-function: ${AWS_LAMBDA_SENTIMENT_FUNCTION:}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8081}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# Logging
logging:
  level:
    com.soulsync: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"